---
- name: playbook
  hosts: all
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: ../Terraformfiles/tf-key-pair.pem
  tasks:    
    - name: Copy files to remote host
      copy:
        src: ../k8sfiles/
        dest: /home/ubuntu/
        mode: 0777
    - name: ls
      command: ls -al
    - name: Update kubeconfig for EKS cluster
      command: aws eks update-kubeconfig --name private-eks-cluster --region eu-west-1
    - name: create namespaces
      command: kubectl apply -f namespace.yaml
    - name: create sa and rbac
      command: kubectl apply -f ServiceAccount.yaml
    - name: create service
      command: kubectl apply -f service.yaml
    - name: create deploy
      command: kubectl apply -f deployment.yaml
